agent: |
  import Agent, { getAgent } from 'npm:@knowlearning/agents/deno.js'

  const xApiAgent = getAgent('xapi.knowlearning.systems')
  Agent.on('child', child => {
      const { environment: { user } } = child
      child.on('mutate', ({ id, scope, patch, context }) => {
          patch.forEach(async ({ path, value }) => {
            if (path[0] === 'xapi' && path.length === 1 && value) {
              const x = await xApiAgent.state(`xapi/${Agent.uuid()}`)
              Object.assign(x, {
                  ...value,
                  source: id,
                  context
              })
            }
          })
      })
  })
